#!/bin/bash
# Regenerates the test runner from the suites in Tests/SillCoreTests.
set -euo pipefail
cd "$(dirname "$0")/.."
python3 - <<'PY'
import re, glob, os
out = ["// Generated by Scripts/gen-test-runner.sh. Do not edit.", "import Foundation", "", "let allTests: [(String, () -> Void)] = ["]
for f in sorted(glob.glob('Tests/SillCoreTests/*.swift')):
    if os.path.basename(f) in ('Support.swift', 'Runner.swift', 'main.swift'):
        continue
    src = open(f).read()
    for suite in re.finditer(r'^struct (\w+) \{(.*?)^\}', src, re.S | re.M):
        name, body = suite.group(1), suite.group(2)
        for m in re.finditer(r'^    func (\w+)\(\) \{', body, re.M):
            out.append(f'    ("{name}.{m.group(1)}", {{ {name}().{m.group(1)}() }}),')
out.append("]")
open('Tests/SillCoreTests/Runner.swift', 'w').write("\n".join(out) + "\n")
print(f"{len(out)-5} tests registered")
PY
